In [14]:
import numpy as np
a = np.array([1,2,3])
print("type: %s"%type(a))
print("Shape: %s"%a.shape)
print(a[0],a[1],a[2])
a[0]=5
print(a)
b= np.array([[1,2,3],[4,5,6]])
print("\n Shape of b: ",b.shape)
print(b[0,0],b[0,1],b[1,0])
a = np.zeros((2,2))
print("\nAll Zeros matrix :\n %s"%a)
b = np.ones((1,2))
print("\nAll ones matrix :\n %s"%b)
d = np.eye(2)
print("\nIdentity Matrix :\n %s"%d)
e = np.random.random((2,2))
print("\n Random Matrix : \n %s"%e)
print("\nVectorized sum example \n")
x = np.array([[1,2],[3,4]])
print("X : \n %s"%x)
print("\nSum : %s"%np.sum(x))
print("\nSum axis = 0: %s"%np.sum(x,axis=0))
print("\nSum axis = 1: %s"%np.sum(x,axis=1))
a=np.arange(10000)
b=np.arange(10000)
dp=np.dot(a,b)
print("\nDot Product :%s \n"%dp)
op=np.outer(a,b)
print("\n outer product :%s \n"%op)
ep = np.multiply(a,b)
print("\n Element wise product: %s \n"%ep)

type: <class 'numpy.ndarray'>
Shape: 3
1 2 3
[5 2 3]

 Shape of b:  (2, 3)
1 2 4

All Zeros matrix :
 [[0. 0.]
 [0. 0.]]

All ones matrix :
 [[1. 1.]]

Identity Matrix :
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 Random Matrix : 
 [[0.15666626 0.24815406]
 [0.07357485 0.88711852]]

Vectorized sum example 

X : 
 [[1 2]
 [3 4]]

Sum : 10

Sum axis = 0: [4 6]

Sum axis = 1: [3 7]

Dot Product :-1724114088 


 outer product :[[       0        0        0 ...        0        0        0]
 [       0        1        2 ...     9997     9998     9999]
 [       0        2        4 ...    19994    19996    19998]
 ...
 [       0     9997    19994 ... 99940009 99950006 99960003]
 [       0     9998    19996 ... 99950006 99960004 99970002]
 [       0     9999    19998 ... 99960003 99970002 99980001]] 


 Element wise product: [       0        1        4 ... 99940009 99960004 99980001] 



In [15]:
import numpy  as np
x = np.array([[1,2],[3,4]])
print("Orginal x: \n%s"%x)
print("\n Transpose of x :\n %s"%x.T)

Orginal x: 
[[1 2]
 [3 4]]

 Transpose of x :
 [[1 3]
 [2 4]]


In [16]:
from numpy import array
from scipy.linalg import svd
A = array([[1,2],[3,4],[5,6]])
print("A :\n %s"%A)
u,s,vt = svd(A)
print("\n U: \n %s"%u)
print("\n S: \n %s"%s)
print("\n VT: \n %s"%vt)

A :
 [[1 2]
 [3 4]
 [5 6]]

 U: 
 [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]

 S: 
 [9.52551809 0.51430058]

 VT: 
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]
